name = "vip"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "vip.mrkings.xyz", custom_domain = true },
  { pattern = "ava.game.naver.com.vip.mrkings.xyz", custom_domain = true },
  { pattern = "quiz.int.vidio.com.vip.mrkings.xyz", custom_domain = true },
  { pattern = "graph.instagram.com.vip.mrkings.xyz", custom_domain = true },
  { pattern = "zaintest.vuclip.com.vip.mrkings.xyz", custom_domain = true },
  { pattern = "support.zoom.us.vip.mrkings.xyz", custom_domain = true },  
  { pattern = "cache.netflix.com.vip.mrkings.xyz", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "63d2aeabd48d4cbeaa1990fe82028944"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "20800721-d3fd-4c1f-81fc-a786f10b2f64"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/MarinaAqua/VPN/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/MarinaAqua/VPN/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/MarinaAqua/VPN/refs/heads/master/web/link.html"
